### ISSUE TITLE
[FEATURE] - Add TW classes as an array of strings

### ISSUE THREAD

**Issue by iobrado** [infinum/eightshift-frontend-libs-tailwind#1]
It would be great if adding Tailwind classes in `manifest.json` would be supported as an array of strings as well, which would allow us to group classes and improve readability.

Now the class list looks like this:
```
"base": {
	"twClasses": "flex items-center justify-between md:justify-start gap-8 max-w-screen-lg mx-auto h-full px-4 md:px-8 lg:px-12 relative",
},
```

As an array, it would look like this:
```
"base": {
	"twClasses": [
		"flex items-center justify-between md:justify-start gap-8",
		"max-w-screen-lg h-full",
		"mx-auto px-4 md:px-8 lg:px-12",
		"relative",
	],
},
```

**Comment by piqusy** [comment]
Been using this for a while, might as well close it 😉
