### ISSUE TITLE
[BUG] - Site footer copy hide if content is missing

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs-tailwind#17]
We need to remove the copy sign if the content is missing  on the frontend
![Screenshot 2024-07-23 at 19 26 12](https://github.com/user-attachments/assets/a4c9ae0a-0306-4201-a3ac-8b74e556a098)

**Comment by goranalkovic-infinum** [comment]
Fixed in 1.2.0
