### ISSUE TITLE
Wrapper Manifest - Gradient direction : to top

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-frontend-libs-tailwind#2]
https://github.com/infinum/eightshift-frontend-libs-tailwind/blob/8d86e065f00ae5a095bffd6059412f3430cb4258/blocks/init/src/Blocks/wrapper/manifest.json#L353

This should be `bg-gradient-to-t`

**Comment by goranalkovic-infinum** [comment]
Open a PR pls 😉

**Comment by piqusy** [comment]
> Open a PR pls 😉

https://github.com/infinum/eightshift-frontend-libs-tailwind/pull/3
