### ISSUE TITLE
[BUG] - Patterns editor missing title

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs-tailwind#21]
No sure if this is us but Patterns editor is missing title once you set it in the modal on the first open. You can change this by going to the code view. We should check if this is caused but us or core

![Screenshot 2024-07-23 at 19 42 10](https://github.com/user-attachments/assets/85d5a916-8b8a-4792-8a9c-a8d6ba56d8dc)

**Comment by goranalkovic-infinum** [comment]
This is Core behavior. My guess is because it prompts you for the name when you add it, that's why it's not shown 🤷
