### ISSUE TITLE
[BUG] - Link inside List item should properly target the tag

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-frontend-libs-tailwind#26]
https://github.com/infinum/eightshift-frontend-libs-tailwind/blob/d49cf51bdd930b8a5771a7b39b7d60d7c3485b83/blocks/init/src/Blocks/components/list/manifest.json#L94

This should be` "twClasses": "font-sans [&_a]:underline font-synthesis-none", ` --- the `>` needs to be replaced wiith `_`

**Comment by goranalkovic-infinum** [comment]
Fixed in 1.2.0
