### ISSUE TITLE
[BUG] - Files need to be pre-formated with the rules from the library 

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-frontend-libs-tailwind#27]
Getting prettier linter errors (`"singleAttributePerLine": true,`)  for components initialized from the library e.g. [video-options.js](https://github.com/infinum/eightshift-frontend-libs-tailwind/blob/main/blocks/init/src/Blocks/components/video/components/video-options.js)

**Comment by goranalkovic-infinum** [comment]
Checked and should be fine in 1.2.0
