### ISSUE TITLE
Use "videoAllowedTypes" attribute from the manifest in component files

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-frontend-libs-tailwind#28]
https://github.com/infinum/eightshift-frontend-libs-tailwind/blob/d49cf51bdd930b8a5771a7b39b7d60d7c3485b83/blocks/init/src/Blocks/components/video/manifest.json#L16

Use the specified attribute as a variable instead of hard-coded strings in `video-editor.js` and `video-options.js` fiels

**Comment by goranalkovic-infinum** [comment]
Fixed in 1.2.0
