### ISSUE TITLE
Icon component has no tailwind base class in manifest

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-frontend-libs-tailwind#30]
https://github.com/infinum/eightshift-frontend-libs-tailwind/blob/6d9ba042f8bc344f23e7e856898d815f50757b46/blocks/init/src/Blocks/components/icon/icon.php#L29

This makes the passed down `$additionalClass` useless since the `Helpers::getTwClasses` method returns empty set when there is nothing in the `$attributes` or the `$manifest` variables

**Comment by goranalkovic-infinum** [comment]
Fixed in 1.4.0
