### ISSUE TITLE
Icon component within a Button component takes on buttons' `$additionalClass`

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-frontend-libs-tailwind#32]
https://github.com/infinum/eightshift-frontend-libs-tailwind/blob/39e92e4eb31c739e3d9d67596359c77d8e555a60/blocks/init/src/Blocks/components/button/button.php#L77

This should be sufficient
```php
echo Helpers::render('icon');
```

**Comment by goranalkovic-infinum** [comment]
Your suggested solution doesn't work.

A temporary fix is to provide blank 'additionalClass'

**Comment by piqusy** [comment]
> Your suggested solution doesn't work.
> 
> A temporary fix is to provide blank 'additionalClass'

It worked in my case, the blank additionalClass would not apply anything to the icons parent button  element

**Comment by piqusy** [comment]
Seems as this has been fixed as it is not an issue anymore ... in a recent update perhaps? 🤔
