### ISSUE TITLE
[BUG] - Button Url is not displayed in the LinkInput input field

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-frontend-libs-tailwind#34]
The value is written in the attributes and properly rendered in the frontend.

```
"@eightshift/frontend-libs-tailwind": "^1.2.0",
"@eightshift/ui-components": "^1.4.6",
```

<img width="1496" alt="image" src="https://github.com/user-attachments/assets/988a5942-f7c3-4dd5-a6de-c6836cfd0f46">

**Comment by goranalkovic-infinum** [comment]
Fixed in Eightshift UI components 1.4.7
