### ISSUE TITLE
[Improvement] - Heading component options has redundant entry in `wrapperProps`

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-frontend-libs-tailwind#50]
The entry in the line below can be moved out with just `tooltip` which should pick up the content from `aria-label` prop

https://github.com/infinum/eightshift-frontend-libs-tailwind/blob/cb1ecb88e21dccc19b8b7f26418a774e6dd58df0/blocks/init/src/Blocks/components/heading/components/heading-options.js#L52

**Comment by goranalkovic-infinum** [comment]
Fixed in 1.4.0
