### ISSUE TITLE
[BUG] - combinations don't work properly with an array of attributes

### ISSUE THREAD

**Issue by iobrado** [infinum/eightshift-frontend-libs-tailwind#53]
After updating my project to FE Libs Tailwind **1.4.1**, I noticed the Tailwind classes from `combinations` aren't applied if passing an array of attributes.

This snippet doesn't apply the listed classes.
```
"combinations": [
			{
				"attributes": {
					"buttonVariant": [
						"primary",
						"secondary"
					]
				},
				"twClasses": "border [&>svg]:size-5 gap-2 py-2 rounded-full"
			},
]
```

But replacing the `buttonVariant` attribute value with a string instead of an array, e.g. `"buttonVariant": "primary"`, solves the issue and the classes are applied.

**Comment by kancijan** [comment]
It's because you should compare at least two attributes. `buttonVariant` is solo here. In this case, I usually use `"buttonUse": true` to make it valid.

**Comment by goranalkovic-infinum** [comment]
@kancijan it's probably something else, the logic for checking whether it matches was rewritten.
