### ISSUE TITLE
[BUG] - Hero hide components if missing content

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs-tailwind#9]
We need to hide buttons if they don't have content

![Screenshot 2024-07-23 at 18 53 21](https://github.com/user-attachments/assets/af2634cb-eaf6-4882-ac55-59998bdb94b5)
![Screenshot 2024-07-23 at 18 53 23](https://github.com/user-attachments/assets/0e28a111-cd48-4f9b-98f0-703cdeab378a)

**Comment by goranalkovic-infinum** [comment]
Fixed in 1.2.0
